INSERT INTO branches (code, name_bn, name_en, type, division, district, address, phone, email, established_date, status)
VALUES
  ('160', 'তানযীমুল উম্মাহ হিফয মাদরাসা, সিলেট শাখা', 'Tanzimul Ummah Hifz Madrasah, Sylhet Branch', 'Hifz Madrasah'::branch_type, 'Sylhet', 'Sylhet', '(), —', null, null, null, 'active'::record_status),
  ('161', 'তানযীমুল উম্মাহ গার্লস হিফয মাদরাসা, কক্সবাজার শাখা', 'Tanzimul Ummah Girls'' Hifz Madrasah, Cox''s Bazar Branch', 'Girls Madrasah'::branch_type, 'Chattogram', 'Cox''s Bazar', '(), —', null, null, null, 'active'::record_status),
  ('162', 'তানযীমুল উম্মাহ হিফয মাদরাসা, বরিশাল শাখা', 'Tanzimul Ummah Hifz Madrasah, Barisal Branch', 'Hifz Madrasah'::branch_type, 'Barishal', 'Barishal', '(), —', null, null, null, 'active'::record_status),
  ('163', 'তানযীমুল উম্মাহ হিফয মাদরাসা, উপশহর-বগুড়া শাখা', 'Tanzimul Ummah Madrasah, Bogura Branch', 'Hifz Madrasah'::branch_type, 'Rajshahi', 'Bogura', '(), —', null, null, null, 'active'::record_status),
  ('164', 'তানযীমুল উম্মাহ গার্লস মাদরাসা, ইবতেদায়ি ও প্রি-হিফয সেকশন', 'Tanzimul Ummah Girls’ Madrasah, Ebtedayee & Pre-Hifz Branch', 'Girls Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Mirpur (মিরপুর), —', null, null, null, 'active'::record_status),
  ('165', 'তানযীমুল উম্মাহ গার্লস মাদরাসা, টাঙ্গাইল শাখা', 'Tanzimul Ummah Girls'' Madrasah, Tangail Branch', 'Girls Madrasah'::branch_type, 'Dhaka', 'Tangail', '(), —', null, null, null, 'active'::record_status),
  ('166', 'তানযীমুল উম্মাহ হিফয মাদরাসা, নোয়াখালী শাখা', 'Tanzimul Ummah Hifz Madrasah, Noakhali Branch', 'Hifz Madrasah'::branch_type, 'Chattogram', 'Noakhali', '(), —', null, null, null, 'active'::record_status),
  ('167', 'তানযীমুল উম্মাহ হিফয মাদরাসা, সাইনবোর্ড শাখা', 'Tanzimul Ummah Hifz Madrasah, Signboard Branch', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', '(), —', null, null, null, 'active'::record_status),
  ('168', 'তানযীমুল উম্মাহ হিফয মাদরাসা, পিরোজপুর শাখা', 'Tanzimul Ummah Hifz Madrasah, Pirojpur Branch', 'Hifz Madrasah'::branch_type, 'Barishal', 'Pirojpur', '(), —', null, null, null, 'active'::record_status),
  ('169', 'তানযীমুল উম্মাহ গার্লস হিফয মাদরাসা, চট্টগ্রাম শাখা', 'Tanzimul Ummah Girls` Hifz Madrasah, Chattogram Branch', 'Girls Madrasah'::branch_type, 'Chattogram', 'Chattogram', '(), —', null, null, null, 'active'::record_status),
  ('170', 'তানযীমুল উম্মাহ গার্লস হিফয মাদরাসা, গাজীপুর শাখা', 'Tanzimul Ummah Girls’ Hifz Madrasah, Gazipur Branch', 'Girls Madrasah'::branch_type, 'Dhaka', 'Gazipur', '(), —', null, null, null, 'active'::record_status),
  ('171', 'তানযীমুল উম্মাহ গার্লস হিফয মাদরসা, মিরপুর শাখা', 'Tanzimul Ummah Girls'' Hifz Madrasah, Mirpur Branch', 'Girls Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Mirpur (মিরপুর), —', null, null, null, 'active'::record_status),
  ('172', 'তানযীমুল উম্মাহ হিফয মাদরাসা, চান্দগাঁও শাখা', 'Tanzimul Ummah Hifz Madrasah, Chandgaon Branch', 'Hifz Madrasah'::branch_type, 'Chattogram', 'Chattogram', '(), —', null, null, null, 'active'::record_status),
  ('173', 'তানযীমুল উম্মাহ হিফয মাদরাসা, মোহাম্মদপুর শাখা', 'Tanzimul Ummah Hifz Madrasah, Mohammadpur Branch', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Mohammadpur (মোহাম্মদপুর), —', null, null, null, 'active'::record_status),
  ('174', 'তানযীমুল উম্মাহ হিফয মাদরাসা, মাধবদী শাখা', 'Tanzimul Ummah Hifz Madrasah, Madhabdi Branch', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Narsingdi', '(), —', null, null, null, 'active'::record_status),
  ('175', 'তানযীমুল উম্মাহ গার্লস হিফয মাদরাসা, যশোর শাখা', 'Tanzimul Ummah Hifz Madrasah, Jashore Branch, Girls'' & Pre-Hifz Section', 'Hifz Madrasah'::branch_type, 'Khulna', 'Jashore', '(), —', null, null, null, 'active'::record_status),
  ('176', 'তানযীমুল উম্মাহ প্রি-হিফয মাদরাসা, মিরপুর শাখা', 'Tanzimul Ummah Pre-Hifz Madrasah, Mirpur Section', 'Pre-Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Mirpur (মিরপুর), —', null, null, null, 'active'::record_status),
  ('177', 'তানযীমুল উম্মাহ প্রি-হিফয মাদরাসা, খুলনা শাখা', 'Tanzimul Ummah Madrasah, Khulna Branch, Ebtedayee & Pre-Hifz Section', 'Pre-Hifz Madrasah'::branch_type, 'Khulna', 'Khulna', '(), —', null, null, null, 'active'::record_status),
  ('178', 'তানযীমুল উম্মাহ গার্লস হিফয মাদরাসা, রংপুর শাখা', 'Girls’ Hifz Madrasah, Rangpur Branch', 'Girls Madrasah'::branch_type, 'Rangpur', 'Rangpur', '(), —', null, null, null, 'active'::record_status),
  ('179', 'তানযীমুল উম্মাহ হিফয মাদরাসা, রংপুর হাজীপাড়া শাখা', 'Tanzimul Ummah Hifz Madrasah, Rangpur Branch, Hajipara Section', 'Hifz Madrasah'::branch_type, 'Rangpur', 'Rangpur', '(), —', null, null, null, 'active'::record_status),
  ('180', 'তানযীমুল উম্মাহ গার্লস হিফয মাদরাসা, লক্ষ্মীপুর শাখা', 'Tanzimul Ummah Hifz Madrasah, Laxmipur Branch, Girls’& Pre-Hifz-Section', 'Hifz Madrasah'::branch_type, 'Chattogram', 'Lakshmipur', '(), —', null, null, null, 'active'::record_status)
ON CONFLICT (code) DO UPDATE SET name_bn=EXCLUDED.name_bn, name_en=EXCLUDED.name_en, type=EXCLUDED.type, division=EXCLUDED.division, district=EXCLUDED.district, address=EXCLUDED.address, phone=EXCLUDED.phone, email=EXCLUDED.email, status=EXCLUDED.status;
