INSERT INTO branches (code, name_bn, name_en, type, division, district, address, phone, email, established_date, status)
VALUES
  ('226', 'তানযীমুল উম্মাহ হিফয মাদরাসা, পিরোজপুর শাখা [গার্লস এন্ড প্রি-হিফয সেকশান]', 'Tanzimul Ummah Hifz Madrasah, Pirojpur Branch [Girls’ & Pre-hifz Section]', 'Hifz Madrasah'::branch_type, 'Barishal', 'Pirojpur', '(), —', null, null, null, 'active'::record_status),
  ('555', 'তানযীমুল উম্মাহ গার্লস হিফয মাদরাসা, পাহাড়তলী শাখা', 'Tanzimul Ummah Girls’ Madrasah, Pahartali Branch', 'Girls Madrasah'::branch_type, 'Chattogram', 'Chattogram', 'Pahartali (পাহাড়তলী), —', null, null, null, 'active'::record_status),
  ('666', 'তানযীমুল উম্মাহ ইন্টারন্যাশনাল তাহফিয স্কুল ও হিফয মাদরাসা, আদাবর শাখা', 'Tanzimul Ummah International Tahfiz School and Hifz Madrasah, Adabar Campus', 'Hifz School'::branch_type, 'Dhaka', 'Dhaka', 'Adabor (আদাবর), —', null, null, null, 'active'::record_status),
  ('6SB', 'তানযীমুল উম্মাহ গার্লস হিফয মাদরাসা, ৬নং সেক্টর শাখা', 'Tanzimul Ummah Girls'' Hifz Madrasah, Sector 6 Branch', 'Girls Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Matamuhuri, (), —', null, null, null, 'active'::record_status),
  ('777', 'তানযীমুল উম্মাহ হিফয মাদরাসা, সিলেট অনাবাসিক শাখা', 'Tanzimul Ummah Hifz Madrasah, Sylhet Non-Residential Branch', 'Hifz Madrasah'::branch_type, 'Sylhet', 'Sylhet', 'Mirabazar (মীরাবাজার), —', null, null, null, 'active'::record_status),
  ('CDBGPS', 'তানযীমুল উম্মাহ হিফয মাদরাসা, চাঁদপুর গার্লস সেকশন', 'Tanzimul Ummah Hifz Madrasah, Chandpur Girls'' Section', 'Girls Madrasah'::branch_type, 'Chattogram', 'Chandpur', '(), —', null, null, null, 'active'::record_status),
  ('DOB', 'তানযীমুল উম্মাহ হিফয মাদরাসা, ধনিয়া শাখা', 'Tanzimul Ummah Hifz Madrasah, Donia Branch', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', '(), —', null, null, null, 'active'::record_status),
  ('GNRB', 'তানযীমুল উম্মাহ হিফয মাদরাসা, অনাবাসিক শাখা, গাজীপুর', 'Tanzimul Ummah Hifz Madrasah, Non-Residential Branch, Gazipur', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Gazipur', '(), —', null, null, null, 'active'::record_status),
  ('JBBGPS', 'তানযীমুল উম্মাহ হিফয মাদরাসা, যাত্রাবাড়ী শাখা [গার্লস এন্ড প্রি-হিফয সেকশান]', 'Tanzimul Ummah Hifz Madrasah, Jatrabari Branch (Girls'' & Pre-Hifz Section)', 'Girls Madrasah'::branch_type, 'Dhaka', 'Narayanganj', '(), —', null, null, null, 'active'::record_status),
  ('JDB', 'তানযীমুল উম্মাহ হিফয মাদরাসা, ঝিনাইদাহ শাখা', 'Tanzimul Ummah Hifz Madrasah, Jhenaidah Branch', 'Hifz Madrasah'::branch_type, 'Khulna', 'Jhenaidah', '(), —', null, null, null, 'active'::record_status),
  ('JUB', 'তানযীমুল উম্মাহ হিফয মাদরাসা, যশোর উপশহর শাখা', 'Tanzimul Ummah Hifz Madrasah, Jessore Uposhahar Branch', 'Hifz Madrasah'::branch_type, 'Khulna', 'Jashore', '(), —', null, null, null, 'active'::record_status),
  ('KGBGPS', 'তানযীমুল উম্মাহ হিফয মাদরাসা, কেরানীগঞ্জ শাখা [গার্লস এন্ড প্রি-হিফয সেকশান]', 'Tanzimul Ummah Hifz Madrasah, Keraniganj Branch (Girls'' & Pre-Hifz Section)', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', '(), —', null, null, null, 'active'::record_status),
  ('MBB', 'তানযীমুল উম্মাহ মাদরাসা, মৌলভীবাজার শাখা', 'Tanzimul Ummah Madrasah, Moulvibazar Branch', 'Hifz Madrasah'::branch_type, 'Sylhet', 'Sylhet', '(), —', null, null, null, 'active'::record_status),
  ('MRBB', 'তানযীমুল উম্মাহ হিফয মাদরাসা, মিরপুর শাখা', 'Tanzimul Ummah Hifz Madrasah, Mirpur Branch', 'Hifz Madrasah'::branch_type, 'ঢাকা', 'ঢাকা', 'বাড়ি #১২, রোড #৭, মিরপুর-১০, ঢাকা', '+8801711223344', 'mirpur.branch@tanzimulummahhifz.org', '2010-01-01', 'active'::record_status),
  ('NKB', 'তানযীমুল উম্মাহ হিফয মাদরাসা, নেত্রকোনা শাখা', 'Tanzimul Ummah Hifz Madrasah, Netrokona Branch', 'Hifz Madrasah'::branch_type, 'Mymensingh', 'Netrokona', '(), —', null, null, null, 'active'::record_status),
  ('NNRB', 'তানযীমুল উম্মাহ হিফয মাদরাসা, নোয়াখালী অনাবাসিক শাখা', 'Tanzimul Ummah Hifz Madrasah, Noakhali Non-Residential Branch', 'Hifz Madrasah'::branch_type, 'Chattogram', 'Noakhali', '(), —', null, null, null, 'active'::record_status),
  ('NRBB', 'তানযীমুল উম্মাহ মাদরাসা, অনাবাসিক শাখা, বরিশাল', 'Tanzimul Ummah Madrasah, Non-Residential Branch, Barisal', 'Hifz Madrasah'::branch_type, 'Barishal', 'Barishal', '(), —', null, null, null, 'active'::record_status),
  ('SRBGPS', 'তানযীমুল উম্মাহ হিফয মাদরাসা, সাতক্ষ্মীরা গার্লস সেকশন', 'Tanzimul Ummah Hifz Madrasah, Satkhira Girls'' Section', 'Girls Madrasah'::branch_type, 'Khulna', 'Satkhira', '(), —', null, null, null, 'active'::record_status),
  ('TUMMB', 'তানযীমুল উম্মাহ মাদরাসা, মিরপুর শাখা', 'Tanzimul Ummah Madrasah, Mirpur Branch', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', '(), —', null, null, null, 'active'::record_status),
  ('TUMMSB', 'তানযীমুল উম্মাহ মাদরাসা, ময়মনসিংহ শাখা', 'Tanzimul Ummah Madrasah, Mymensingh Branch', 'Hifz Madrasah'::branch_type, 'Mymensingh', 'Mymensingh', '(), —', null, null, null, 'active'::record_status),
  ('TUMRB', 'তানযীমুল উম্মাহ মাদরাসা, রাজশাহী শাখা', 'Tanzimul Ummah Madrasah, Rajshahi Branch', 'Hifz Madrasah'::branch_type, 'Rajshahi', 'Rajshahi', '(), —', null, null, null, 'active'::record_status)
ON CONFLICT (code) DO UPDATE SET name_bn=EXCLUDED.name_bn, name_en=EXCLUDED.name_en, type=EXCLUDED.type, division=EXCLUDED.division, district=EXCLUDED.district, address=EXCLUDED.address, phone=EXCLUDED.phone, email=EXCLUDED.email, status=EXCLUDED.status;
