INSERT INTO branches (code, name_bn, name_en, type, division, district, address, phone, email, established_date, status)
VALUES
  ('181', 'তানযীমুল উম্মাহ ইন্টারন্যাশনাল তাহফীয স্কুল, গার্লস সেকশন', 'Tanzimul Ummah International Tahfiz School, Girls'' Section', 'Alim Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Uttara (উত্তরা), —', null, null, null, 'active'::record_status),
  ('182', 'তানযীমুল উম্মাহ হিফয মাদরাসা, কক্সবাজার শাখা, প্রি-হিফয সেকশন', 'Tanzimul Ummah Hifz Madrasah, Cox’s Bazar Branch, Pre-Hifz Section', 'Hifz Madrasah'::branch_type, 'Chattogram', 'Cox''s Bazar', '(), —', null, null, null, 'active'::record_status),
  ('183', 'তানযীমুল উম্মাহ হিফয মাদরাসা, রাজশাহী শাখা [পদ্মা আবাসিক সেকশন]', 'Tanzimul Ummah Hifz Madrasah, Rajshahi Branch, Padma Residential Section', 'Hifz Madrasah'::branch_type, 'Rajshahi', 'Rajshahi', '(), —', null, null, null, 'active'::record_status),
  ('184', 'তানযীমুল উম্মাহ হিফয মাদরাসা, মোহাম্মদপুর শাখা, গার্লস অ্যান্ড প্রি-হিফয সেকশন', 'Tanzimul Ummah Hifz Madrasah, Mohammadpur Branch, Girls'' & Pre-Hifz Section', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Mohammadpur (মোহাম্মদপুর), —', null, null, null, 'active'::record_status),
  ('185', 'তানযীমুল উম্মাহ ইন্টারন্যশনাল তাহফিয স্কুল, প্রিপারেটরি ক্যাম্পাস', 'Tanzimul Ummah International Tahfiz School, Preparatory Section', 'Alim Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Uttara (উত্তরা), —', null, null, null, 'active'::record_status),
  ('186', 'তানযীমুল উম্মাহ মাদরাসা, নারায়ণগঞ্জ শাখা, প্রি-হিফয ও ইবতেদায়ি সেকশন', 'Tanzimul Ummah Madrasah, Narayanganj Branch, Ebtedayee & Pre-Hifz Section', 'Alim Madrasah'::branch_type, 'Unknown', 'Unknown', null, null, null, null, 'active'::record_status),
  ('187', 'তানযীমুল উম্মাহ গার্লস হিফয মাদরাসা, রাজশাহী শাখা', 'Girl''s Hifz Madrasah, Rahshahi Branch', 'Girls Madrasah'::branch_type, 'Rajshahi', 'Rajshahi', '(), —', null, null, null, 'active'::record_status),
  ('188', 'তানযীমুল উম্মাহ হিফয় মাদরাসা,ময়মনসিংহ শাখা নাহার রোড সেকশন', 'Tanzimul Ummah Hifz Madrasah Mymensingh Branch Naha Road Section', 'Hifz Madrasah'::branch_type, 'Mymensingh', 'Mymensingh', 'Char Fesson, Naha Road (নাহার রোড), —', null, null, null, 'active'::record_status),
  ('189', 'তানযীমুল উম্মাহ হিফয মাদরাসা, যাত্রাবাড়ী শাখা', 'Tanzimul Ummah Hifz Madrasah, Jatrabari Branch', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', '(), —', null, null, null, 'active'::record_status),
  ('190', 'তানযীমুল উম্মাহ মাদরাসা, বগুড়া শাখা [গার্লস সেকশন]', 'Tanzimul Ummah Madrasah, Bogura Branch, Genarels Section.', 'Alim Madrasah'::branch_type, 'Rajshahi', 'Bogura', '(), —', null, null, null, 'active'::record_status),
  ('191', 'তানযীমুল উম্মাহ হিফয মাদরাসা, খুলনা অনাবাসিক শাখা', 'Tanzimul Ummah Hifz Madrasah, Khulna Branch, Non residential Section', 'Hifz Madrasah'::branch_type, 'Khulna', 'Khulna', '(), —', null, null, null, 'active'::record_status),
  ('192', 'তানযীমুল উম্মাহ গার্লস হিফয মাদরাসা, চান্দগাঁও শাখা', 'Tanzimul Ummah Hifz Madrasah, Chandgaon Branch, Girls'' & Pre-Hifz Section', 'Hifz Madrasah'::branch_type, 'Chattogram', 'Chattogram', 'Chandgaon (চাঁদগাও), —', null, null, null, 'active'::record_status),
  ('193', 'তানযীমুল উম্মাহ হিফয মাদরাসা, আল-আরক্বাম অনাবাসিক শাখা', 'Tanzimul Ummah Hifz Madrasah, Al-Arqam Non Residential Branch', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Uttara (উত্তরা), —', null, null, null, 'active'::record_status),
  ('195', 'তানযীমুল উম্মাহ মাদরাসা, যশোর শাখা', 'Tanzimul Ummah Hifz Madrasah, Jashore Branch. Non-Residential Hifz & General Section', 'Hifz Madrasah'::branch_type, 'Khulna', 'Jashore', '(), —', null, null, null, 'active'::record_status),
  ('196', 'তানযীমুল উম্মাহ হিফয মাদরাসা, ১০নং সেক্টর শাখা', 'Tanzimul Ummah Hifz Madrasah, 10 Number Sector Branch', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Uttara (উত্তরা), —', null, null, null, 'active'::record_status),
  ('197', 'তানযীমুল উম্মাহ হিফয মাদরাসা, মিরপুর শাখা-অনাবাসিক সেকশন', 'Tanzimul Ummah Hifz Madrasah, Mirpur Branch, Non-Residential Section', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Mirpur (মিরপুর), —', null, null, null, 'active'::record_status),
  ('198', 'তানযীমুল উম্মাহ গার্লস হিফয মাদরাসা, নোয়াখালী শাখা', 'Tanzimul Ummah Girls’ Hifz Madrasah, Noakhali Branch', 'Girls Madrasah'::branch_type, 'Chattogram', 'Noakhali', '(), —', null, null, null, 'active'::record_status),
  ('199', 'তানযীমুল উম্মাহ গার্লস হিফয মাদরাসা, খুলনা শাখা', 'Tanzimul Ummah Girls’ Hifz Madrasah, Khulna Branch', 'Girls Madrasah'::branch_type, 'Khulna', 'Khulna', '(), —', null, null, null, 'active'::record_status),
  ('200', 'তানযীমুল উম্মাহ প্রি-হিফয মাদরাসা, যশোর শাখা', 'Tanzimul Ummah Girls'' Hifz Madrasah, Jashore Branch', 'Hifz Madrasah'::branch_type, 'Khulna', 'Jashore', '(), —', null, null, null, 'active'::record_status),
  ('201', 'তানযীমুল উম্মাহ হিফয মাদরাসা বগুড়া শাখা [গার্লস অ্যান্ড প্রি- হিফয অনাবাসিক সেকশন]', 'Tanzimul Ummah Hifz Madrasah, Bogura Branch [Girls’ & Pre-hifz Non-Residential Section]', 'Hifz Madrasah'::branch_type, 'Rajshahi', 'Bogura', '(), —', null, null, null, 'inactive'::record_status),
  ('202', 'তানযীমুল উম্মাহ মাদরাসা, বগুড়া শাখা', 'Tanzimul Ummah Madrasah, Bogura Branch', 'Alim Madrasah'::branch_type, 'Rajshahi', 'Bogura', '(), —', null, null, null, 'active'::record_status)
ON CONFLICT (code) DO UPDATE SET name_bn=EXCLUDED.name_bn, name_en=EXCLUDED.name_en, type=EXCLUDED.type, division=EXCLUDED.division, district=EXCLUDED.district, address=EXCLUDED.address, phone=EXCLUDED.phone, email=EXCLUDED.email, status=EXCLUDED.status;
