INSERT INTO branches (code, name_bn, name_en, type, division, district, address, phone, email, established_date, status)
VALUES
  ('136', 'তানযীমুল উম্মাহ মাদরাসা, নারায়নগঞ্জ শাখা', 'Tanzimul Ummah Madrasah, Narayanganj Branch', 'Alim Madrasah'::branch_type, 'Dhaka', 'Narayanganj', '(), —', null, null, null, 'active'::record_status),
  ('139', 'তানযীমুল উম্মাহ মাদরাসা, খুলনা শাখা', 'Tanzimul Ummah Madrasah, Khulna Branch', 'Alim Madrasah'::branch_type, 'Khulna', 'Khulna', '(), —', null, null, null, 'active'::record_status),
  ('140', 'তানযীমুল উম্মাহ হিফয মাদরাসা, রাজশাহী শাখা', 'Tanzimul Ummah Hifz Madrasah, Rajshahi Branch', 'Hifz Madrasah'::branch_type, 'Rajshahi', 'Rajshahi', 'Shibpur, (), —', null, null, null, 'active'::record_status),
  ('141', 'তানযীমুল উম্মাহ আলিম মাদরাসা, স্থায়ী ক্যাম্পাস, আশুলিয়া', 'Tanzimul Ummah Alim Madrasah, Permanent Campus Ashulia', 'Alim Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Ashulia (আশুলিয়া), —', null, null, null, 'active'::record_status),
  ('142', 'তানযীমুল উম্মাহ হিফয মাদরাসা, অনাবাসিক শাখা', 'Tanzimul Ummah Hifz Madrasah, Non Residential Branch', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Uttara (উত্তরা), —', null, null, null, 'active'::record_status),
  ('143', 'তানযীমুল উম্মাহ গার্লস মাদরাসা, চট্টগ্রাম শাখা', 'Tanzimul Ummah Girls'' Madrasah, Chittagang Branch', 'Girls Madrasah'::branch_type, 'Chattogram', 'Chattogram', '(), —', null, null, null, 'active'::record_status),
  ('144', 'তানযীমুল উম্মাহ গার্লস মাদরাসা, ফেনী শাখা', 'Tanzimul Ummah Girls'' Madrasah, Feni Branch', 'Girls Madrasah'::branch_type, 'Chattogram', 'Feni', '(), —', null, null, null, 'active'::record_status),
  ('145', 'তানযীমুল উম্মাহ মাদরাসা, বরিশাল শাখা', 'Tanzimul Ummah Madrasah, Barisal Branch', 'Alim Madrasah'::branch_type, 'Barishal', 'Barishal', '(), —', null, null, null, 'active'::record_status),
  ('146', 'তানযীমুল উম্মাহ হিফয মাদরাসা, কক্সবাজার শাখা', 'Tanzimul Ummah Hifz Madrasah, Cox`s Bazar Branch', 'Hifz Madrasah'::branch_type, 'Chattogram', 'Cox''s Bazar', '(), —', null, null, null, 'active'::record_status),
  ('147', 'তানযীমুল উম্মাহ হিফয মাদরাসা, খুলনা শাখা', 'Tanzimul Ummah Hifz Madrasah, Khulna Branch', 'Hifz Madrasah'::branch_type, 'Khulna', 'Khulna', '(), —', null, null, null, 'active'::record_status),
  ('148', 'তানযীমুল উম্মাহ হিফয মাদরাসা, রংপুর শাখা', 'Tanzimul ummah Hifz Madrasah, Rangpur Branch', 'Hifz Madrasah'::branch_type, 'Rangpur', 'Rangpur', '(), —', null, null, null, 'active'::record_status),
  ('149', 'তানযীমুল উম্মাহ হিফয মাদরাসা, বগুড়া রহমান নগর শাখা', 'Tanzimul Ummah Hifz Madrasah, Bogura Branch', 'Hifz Madrasah'::branch_type, 'Rajshahi', 'Bogura', '(), —', null, null, null, 'active'::record_status),
  ('150', 'তানযীমুল উম্মাহ হিফয মাদরাসা, লক্ষ্মীপুর শাখা', 'Tanzimul Ummah Hifz Madrasah, Lakshmipur Branch', 'Hifz Madrasah'::branch_type, 'Chattogram', 'Lakshmipur', 'Mohonpur, (), —', null, null, null, 'active'::record_status),
  ('151', 'তানযীমুল উম্মাহ হিযয মাদরাসা, মিরপুর শাখা', 'Tanzimul Ummah Madrasah, Mirpur Branch', 'Alim Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Mirpur (মিরপুর), —', null, null, null, 'active'::record_status),
  ('152', 'তানযীমুল উম্মাহ হিফয মাদরাসা, বারিধারা শাখা', 'Tanzimul Ummah Hifz Madrasah, Baridhara Branch', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Baridhara (বারিধারা), —', null, null, null, 'active'::record_status),
  ('153', 'তানযীমুল উম্মাহ গার্লস মাদরাসা, খুলনা শাখা', 'Tanzimul Ummah Girls'' Madrasah, Khulna Branch', 'Alim Madrasah'::branch_type, 'Khulna', 'Khulna', '(), —', null, null, null, 'active'::record_status),
  ('155', 'তানযীমুল উম্মাহ গার্লস হিফয মাদরাসা, অনাবাসিক শাখা', 'Tanzimul Ummah Girls'' Hifz Madrasah, Non residential Branch', 'Girls Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Uttara (উত্তরা), —', null, null, null, 'active'::record_status),
  ('156', 'তানযীমুল উম্মাহ ইন্টারন্যাশনাল তাহফিয স্কুল, বয়েজ ক্যাম্পাস', 'Tanzimul Ummah International Tahfiz School, Boys'' Campus', 'Alim Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Uttara (উত্তরা), —', null, null, null, 'active'::record_status),
  ('157', 'তানযীমুল উম্মাহ হিফয মাদরাসা, পাহাড়তলী শাখা', 'Tanzimul Ummah Hifz Madrasah, Pahartali Branch', 'Hifz Madrasah'::branch_type, 'Chattogram', 'Chattogram', '(), —', null, null, null, 'active'::record_status),
  ('158', 'তানযীমুল উম্মাহ হিফয মাদরাসা, ময়মনসিংহ শাখা', 'Tanzimul Ummah Hifz Madrasah, Mymensingh Branch', 'Alim Madrasah'::branch_type, 'Mymensingh', 'Mymensingh', '(), —', null, null, null, 'active'::record_status),
  ('159', 'তানযীমুল উম্মাহ হিফয মাদরাসা, যশোর শাখা', 'Tanzimul Ummah Hifz Madrasah, Jashore Branch', 'Hifz Madrasah'::branch_type, 'Khulna', 'Jashore', '(), —', null, null, null, 'active'::record_status)
ON CONFLICT (code) DO UPDATE SET name_bn=EXCLUDED.name_bn, name_en=EXCLUDED.name_en, type=EXCLUDED.type, division=EXCLUDED.division, district=EXCLUDED.district, address=EXCLUDED.address, phone=EXCLUDED.phone, email=EXCLUDED.email, status=EXCLUDED.status;
