INSERT INTO branches (code, name_bn, name_en, type, division, district, address, phone, email, established_date, status)
VALUES
  ('203', 'তানযীমুল উম্মাহ হিফয মাদরাসা, রংপুর শাখা [প্রি-হিফয সেকশান]', 'Tanzimul Ummah Hifz Madrasah, Rangpur Branch [Pre-hifz Section]', 'Hifz Madrasah'::branch_type, 'Rangpur', 'Rangpur', '(), —', null, null, null, 'active'::record_status),
  ('204', 'তানযীমুল উম্মাহ হিফয মাদরাসা, দক্ষিণখান, গার্লস অ্যান্ড প্রি-হিফয সেকশন', 'Tanzimul Ummah Hifz Madrasah, Dokkhinkhan Branch [Girls’ & Pre-hifz Section]', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Uttara (উত্তরা), —', null, null, null, 'active'::record_status),
  ('205', 'তানযীমুল উম্মাহ গার্লস মাদরাসা, বরিশাল শাখা', 'Tanzimul Ummah Girls’ Madrasah, Barishal Branch', 'Girls Madrasah'::branch_type, 'Barishal', 'Barishal', '(), —', null, null, null, 'active'::record_status),
  ('206', 'তানযীমুল উম্মাহইন্টার ন্যাশনাল তাহফিয স্কুল, জুনিয়র ক্যাম্পাস', 'Tanzimul Ummah International Tahfiz School, Junior Campus', 'Hifz School'::branch_type, 'Dhaka', 'Dhaka', 'Uttara (উত্তরা), —', null, null, null, 'active'::record_status),
  ('207', 'তানযীমুল উম্মাহ হিফয মাদরাসা, নারায়ণগঞ্জ শহর শাখা', 'Tanzimul Ummah Hifz Madrasah, Narayangonj Branch', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Narayanganj', '(), —', null, null, null, 'active'::record_status),
  ('208', 'তানযীমুল উম্মাহ হিফয মাদরাসা ময়মনসিংহ শাখা (গার্লস অ্যান্ড প্রি-হিফয সেকশন)', 'Tanzimul Ummah Hifz Madrasah Mymanshingha Branch [Girls’ & Pre-hifz Section]', 'Hifz Madrasah'::branch_type, 'Mymensingh', 'Mymensingh', '(), —', null, null, null, 'active'::record_status),
  ('209', 'তানযীমুল উম্মাহ হিফয মাদরাসা, মাদারীপুর শাখা', 'Tanzimul Ummah Hifz Madrasah, Madaripur Branch', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Madaripur', '(), —', null, null, null, 'active'::record_status),
  ('210', 'তানযীমুল উম্মাহ হিফয মাদরাসা, কুমিল্লা শাখা', 'Tanzimul Ummah Hifz Madrasah, Comilla Branch', 'Hifz Madrasah'::branch_type, 'Chattogram', 'Cumilla', '(), —', null, null, null, 'active'::record_status),
  ('211', 'তানযীমুল উম্মাহ হিফয মাদরাসা, কেরানীগঞ্জ শাখা', 'Tanzimul Ummah Hifz Madrasah, Keraniganj Branch', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', '(), —', null, null, null, 'active'::record_status),
  ('212', 'তানযীমুল উম্মাহ হিফয মাদরাসা, সাতক্ষীরা শাখা', 'Tanzimul Ummah Hifz Madrasah, Satkhira Branch', 'Hifz Madrasah'::branch_type, 'Khulna', 'Jashore', '(), —', null, null, null, 'active'::record_status),
  ('213', 'তানযীমুল উম্মাহ হিফয মাদরাসা, চাঁদপুর শাখা', 'Tanzimul Ummah Hifz Madrasah, Chadpur Branch', 'Hifz Madrasah'::branch_type, 'Chattogram', 'Chandpur', '(), —', null, null, null, 'active'::record_status),
  ('214', 'তানযীমুল উম্মাহ হিফয মাদরাসা, ৬ নং সেক্টর শাখা', 'Tanzimul Ummah Hifz Madrasah, 6 Number Sector Branch', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Uttara (উত্তরা), —', null, null, null, 'active'::record_status),
  ('216', 'তানযীমুল উম্মাহ হিফয মাদরাসা, অনাবাসিক শাখা, রাজশাহী', 'Tanzimul Ummah Hifz Madrasah, Non-Residentioan Branch, Rajshahi', 'Hifz Madrasah'::branch_type, 'Rajshahi', 'Rajshahi', '(), —', null, null, null, 'active'::record_status),
  ('217', 'তানযীমুল উম্মাহ মাদরাসা, রংপুর শাখা', 'Tanzimul Ummah Madrasah, Rangpur Branch', 'Alim Madrasah'::branch_type, 'Rangpur', 'Rangpur', '(), —', null, null, null, 'active'::record_status),
  ('218', 'তানযীমুল উম্মাহ গার্লস মাদরাসা, হালিশহর শাখা', 'Tanzimul Ummah Girls’ Madrasah, Halishahar Branch', 'Girls Madrasah'::branch_type, 'Chattogram', 'Chattogram', '(), —', null, null, null, 'active'::record_status),
  ('219', 'তানযীমুল উম্মাহ হিফয মাদরাসা, কল্পলোক শাখা', 'Tanzimul Ummah Hifz Madrasah, Kolpolok Branch', 'Hifz Madrasah'::branch_type, 'Chattogram', 'Chattogram', '(), —', null, null, null, 'active'::record_status),
  ('221', 'তানযীমুল উম্মাহ হিফয মাদরাসা, সাইনবোর্ড শাখা, গার্লস অ্যান্ড প্রি-হিফয সেকশন', 'Tanzimul Ummah Hifz Madrasah, Signboard Branch [Girls’ & Pre-hifz Section]', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Dhaka', 'Matamuhuri, (), —', null, null, null, 'active'::record_status),
  ('222', 'তানযীমুল উম্মাহ হিফয মাদরাসা, পাহাড়তলী অনাবাসিক শাখা', 'Tanzimul Ummah Hifz Madrasah, Pahartali Branch, Non-Residential', 'Hifz Madrasah'::branch_type, 'Chattogram', 'Chattogram', '(), —', null, null, null, 'active'::record_status),
  ('223', 'তানযীমুল উম্মাহ হিফয মাদরাসা, টাঙ্গাইল শাখা, প্রি-হিফয সেকশন', 'Tanzimul Ummah Hifz Madrasah, Tangail Branch [Pre-hifz Section]', 'Hifz Madrasah'::branch_type, 'Dhaka', 'Tangail', '(), —', null, null, null, 'active'::record_status),
  ('224', 'তানযীমুল উম্মাহ হিফয মাদরাসা, অনাবাসিক শাখা, ফেনী', 'Tanzimul Ummah Hifz Madrasah, Non-Residential Branch, Feni', 'Hifz Madrasah'::branch_type, 'Chattogram', 'Feni', '(), —', null, null, null, 'active'::record_status),
  ('225', 'তানযীমুল উম্মাহ হিফয মাদরাসা, রাজশাহী শাখা, প্রি-হিফয সেকশন', 'Tanzimul Ummah Hifz Madrasah, Rajshahi Branch [Pre-hifz Section]', 'Hifz Madrasah'::branch_type, 'Rajshahi', 'Rajshahi', '(), —', null, null, null, 'active'::record_status)
ON CONFLICT (code) DO UPDATE SET name_bn=EXCLUDED.name_bn, name_en=EXCLUDED.name_en, type=EXCLUDED.type, division=EXCLUDED.division, district=EXCLUDED.district, address=EXCLUDED.address, phone=EXCLUDED.phone, email=EXCLUDED.email, status=EXCLUDED.status;
